version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      target-branch: 'main'
      open-pull-requests-limit: 20
      labels:
          - 'dependencies'
    - package-ecosystem: 'gitsubmodule'
      directory: '/'
      schedule:
          interval: 'weekly'
      target-branch: 'main'
      labels:
          - 'dependencies'